runtime: python39  # Use the appropriate Python version

entrypoint: gunicorn -b :$PORT main:app  # Use Gunicorn as the web server

env_variables:
  FLASK_ENV: production  # Set Flask environment to production
  #SECRET_KEY: your_secret_key  # Replace with your actual secret key

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

# Add other configurations as needed
